# Generated by Django 5.0.6 on 2024-07-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ammunation', '0018_alter_arma_calibre_alter_perfil_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='calibre',
            field=models.CharField(choices=[('subfusil', 'subfusil'), ('fusil', 'fusil'), ('pistola', 'pistola'), ('francotirador', 'francotirador'), ('escopeta', 'escopeta')], max_length=13),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ciudad',
            field=models.CharField(choices=[('Concepción', 'Concepción'), ('curanilahue', 'curanilahue'), ('colina', 'colina')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PREPARADO', 'PREPARADO'), ('ENTREGADO', 'ENTREGADO'), ('EN PREPARACIÓN', 'EN PREPARACIÓN'), ('ENVIADO', 'ENVIADO')], default='EN PREPARACIÓN', max_length=30),
        ),
    ]
