# Generated by Django 5.0.6 on 2024-07-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ammunation', '0019_alter_arma_calibre_alter_perfil_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='calibre',
            field=models.CharField(choices=[('subfusil', 'subfusil'), ('fusil', 'fusil'), ('francotirador', 'francotirador'), ('escopeta', 'escopeta'), ('pistola', 'pistola')], max_length=13),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ciudad',
            field=models.CharField(choices=[('Concepción', 'Concepción'), ('colina', 'colina'), ('curanilahue', 'curanilahue')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('ENTREGADO', 'ENTREGADO'), ('ENVIADO', 'ENVIADO'), ('PREPARADO', 'PREPARADO'), ('EN PREPARACIÓN', 'EN PREPARACIÓN')], default='EN PREPARACIÓN', max_length=30),
        ),
    ]
