# Generated by Django 5.0.6 on 2024-07-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ammunation', '0020_alter_arma_calibre_alter_perfil_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='calibre',
            field=models.CharField(choices=[('pistola', 'pistola'), ('subfusil', 'subfusil'), ('escopeta', 'escopeta'), ('francotirador', 'francotirador'), ('fusil', 'fusil')], max_length=13),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ciudad',
            field=models.CharField(choices=[('colina', 'colina'), ('curanilahue', 'curanilahue'), ('Concepción', 'Concepción')], max_length=15, null=True),
        ),
    ]
