# Generated by Django 5.0.2 on 2024-07-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ammunation', '0021_alter_arma_calibre_alter_perfil_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='calibre',
            field=models.CharField(choices=[('subfusil', 'subfusil'), ('escopeta', 'escopeta'), ('pistola', 'pistola'), ('fusil', 'fusil'), ('francotirador', 'francotirador')], max_length=13),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ciudad',
            field=models.CharField(choices=[('curanilahue', 'curanilahue'), ('colina', 'colina'), ('Concepción', 'Concepción')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('EN PREPARACIÓN', 'EN PREPARACIÓN'), ('ENVIADO', 'ENVIADO'), ('ENTREGADO', 'ENTREGADO'), ('PREPARADO', 'PREPARADO')], default='EN PREPARACIÓN', max_length=30),
        ),
    ]
